/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Usuario;
import model.dao.UsuarioDAO;

/**
 *
 * @author laert
 */
public class CadastroUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUsuario
     */
    String action = "";
    
    public CadastroUsuarios() {
        initComponents();
        Botoes(true, true, false, false);
        Campos(false);
        painel_dados.setVisible(false);
    }
    
    public void Botoes(boolean Novo, boolean Alterar, boolean Salvar, boolean Cancelar){
        btnNovo.setEnabled(Novo);
        btnAlterar.setEnabled(Alterar);
        btnSalvar.setEnabled(Salvar);
        btnCancelar.setEnabled(Cancelar);
    }
    
    public void Campos(boolean a){
        txt_login.setEnabled(a);
        txt_senha.setEnabled(a);
        txt_resenha.setEnabled(a);
        cb_status.setEnabled(a);
        cb_tipo.setEnabled(a);
        
        txt_login.setText("");
        txt_resenha.setText("");
        txt_senha.setText("");
        cb_status.setSelectedIndex(0);
        cb_tipo.setSelectedIndex(0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        painel_dados = new javax.swing.JPanel();
        txt_resenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txt_senha = new javax.swing.JPasswordField();
        painel_alterar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N

        setClosable(true);
        setTitle("Cadastrar Usuário");
        setPreferredSize(new java.awt.Dimension(350, 250));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 73, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, 175, 136));

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovo.setText("CADASTRAR");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 114, 64));

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 114, 64));

        painel_dados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do Usuário"));
        painel_dados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painel_dados.add(txt_resenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 103, 108, -1));

        jLabel1.setText("Login:");
        painel_dados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 30, -1, -1));

        jLabel2.setText("Senha:");
        painel_dados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 68, -1, -1));

        jLabel3.setText("Re-Senha:");
        painel_dados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 106, -1, -1));
        painel_dados.add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 27, 108, -1));

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        painel_dados.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 27, 94, 50));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        painel_dados.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 88, 94, 54));
        painel_dados.add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 65, 108, -1));

        jLabel7.setText("Tipo:");

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Ativo", "Inativo" }));

        jLabel8.setText("Status:");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Gerência", "Supervisão" }));

        javax.swing.GroupLayout painel_alterarLayout = new javax.swing.GroupLayout(painel_alterar);
        painel_alterar.setLayout(painel_alterarLayout);
        painel_alterarLayout.setHorizontalGroup(
            painel_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_alterarLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(painel_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        painel_alterarLayout.setVerticalGroup(
            painel_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_alterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_alterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_dados.add(painel_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 129, -1, -1));

        getContentPane().add(painel_dados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, 314, 207));

        setSize(new java.awt.Dimension(346, 401));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Botoes(true, true, false, false);
        Campos(false);
        painel_dados.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Usuario u =  new Usuario();
        UsuarioDAO dao = new UsuarioDAO();
        
        boolean isUser = false;
        boolean isValid = false;
        
        String login = txt_login.getText();
        String senha = String.valueOf(txt_senha.getPassword());
        String resenha = String.valueOf(txt_resenha.getPassword());
        
        if (login.length() >=1 && senha.length() >=1) {
            if (senha.equals(resenha)) {
                isUser = dao.checkUser(login);
                isValid = true;
                if (isUser && action.equals("Novo")) {
                    JOptionPane.showMessageDialog(null, "Já existe um Usuário com esse login!");

                }
            }else{
                JOptionPane.showMessageDialog(this, "As senhas são diferentes!");
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Verifique os dados informados!");
        }
        
        UsuarioDAO udao = new UsuarioDAO();
        u.setLogin(login);
        u.setSenha(senha);
                
        if (isValid) {
             if (isUser==false && action.equals("Novo")){
                u.setStatus(1);
                u.setTipo(1);
                udao.create(u);
            }else if(isUser==true && action.equals("Alterar")){
                u.setTipo(cb_tipo.getSelectedIndex());
                u.setStatus(cb_status.getSelectedIndex());
                udao.update(u);
            }
        }
        
        Botoes(true, true, false, false);
        Campos(false);
        painel_dados.setVisible(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        action = "Novo";
        Botoes(false, false, true, true);
        Campos(true);
        painel_dados.setVisible(true);
        painel_alterar.setVisible(false);
        btnSalvar.setText("Cadastrar");
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        action = "Alterar";
        Botoes(false, false, true, true);
        Campos(true);
        painel_dados.setVisible(true);
        painel_alterar.setVisible(true);
        btnSalvar.setText("Alterar");
    }//GEN-LAST:event_btnAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel painel_alterar;
    private javax.swing.JPanel painel_dados;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_resenha;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables
}
