/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Cargo;
import model.dao.CargoDAO;

/**
 *
 * @author laert
 */
public class CadastroCargos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCargos
     */
    String action = "Padrao";
    
    public CadastroCargos() {
        initComponents();
//        DefaultTableModel modelo = (DefaultTableModel) tbl_cargo.getModel();
//        tbl_cargo.setRowSorter(new TableRowSorter(modelo));
        LoadTableCargo();
        Botoes(true, false, false, false, false);
        Campos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cargo = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_cargo_codigo = new javax.swing.JTextField();
        txt_cargo_nome = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Cargos");
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);

        tbl_cargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cargoMouseClicked(evt);
            }
        });
        tbl_cargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_cargoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_cargo);
        if (tbl_cargo.getColumnModel().getColumnCount() > 0) {
            tbl_cargo.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbl_cargo.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        btnNovo.setText("Novo");
        btnNovo.setPreferredSize(new java.awt.Dimension(60, 25));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setMaximumSize(new java.awt.Dimension(60, 25));
        btnEditar.setMinimumSize(new java.awt.Dimension(60, 25));
        btnEditar.setPreferredSize(new java.awt.Dimension(60, 25));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(75, 23));
        btnExcluir.setMinimumSize(new java.awt.Dimension(75, 23));
        btnExcluir.setPreferredSize(new java.awt.Dimension(60, 25));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));

        btnSalvar.setText("Salvar");
        btnSalvar.setMaximumSize(new java.awt.Dimension(75, 23));
        btnSalvar.setMinimumSize(new java.awt.Dimension(75, 23));
        btnSalvar.setPreferredSize(new java.awt.Dimension(75, 23));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Código:");

        jLabel9.setText("Nome:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cargo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cargo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cargo_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_cargo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 400, 480);
    }// </editor-fold>//GEN-END:initComponents

    public void LoadTableCargo(){
        DefaultTableModel modelo = (DefaultTableModel) tbl_cargo.getModel();
        modelo.setNumRows(0);
        CargoDAO cdao = new CargoDAO();

        for (Cargo c: cdao.read()) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getCodigo(),
                c.getNome(),
            });

        }
 
    }
    
    public void Botoes(boolean N, boolean E, boolean D, boolean S, boolean C){
        btnNovo.setEnabled(N);
        btnEditar.setEnabled(E);
        btnExcluir.setEnabled(D);
        btnSalvar.setEnabled(S);
        btnCancelar.setEnabled(C);
    }
    
    public void Campos(boolean action){
        txt_cargo_codigo.setEnabled(action);
        txt_cargo_nome.setEnabled(action);
    }
    
    private void tbl_cargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cargoMouseClicked

        if (tbl_cargo.getSelectedRow() != -1) {
            txt_cargo_codigo.setText(tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),1).toString());
            txt_cargo_nome.setText(tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),2).toString());
        }
        Botoes(true, true, true, false, false);
    }//GEN-LAST:event_tbl_cargoMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        Botoes(false, false, false, true, true);
        Campos(true);
        action = "Novo";
        txt_cargo_codigo.setText("");
        txt_cargo_nome.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Botoes(false, false, false, true, true);
        Campos(true);
        action = "Editar";
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (tbl_cargo.getSelectedRow() != -1) {
            Cargo c = new Cargo();
            CargoDAO dao = new CargoDAO();
            c.setId((int)tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),0));
            
            dao.delete(c);
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
        
        txt_cargo_codigo.setText("");
        txt_cargo_nome.setText("");
        
        LoadTableCargo();
        Botoes(true, false, false, false, false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Cargo c = new Cargo();
        CargoDAO dao = new CargoDAO();
        
        c.setCodigo(Integer.parseInt(txt_cargo_codigo.getText()));
        c.setNome(txt_cargo_nome.getText());
        
        if (action.equals("Novo")) {
            dao.create(c);
        }else if(action.equals("Editar")){
            c.setId((int)tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),0));
            dao.update(c);
        }
        
        txt_cargo_codigo.setText("");
        txt_cargo_nome.setText("");
        LoadTableCargo();
        Botoes(true, false, false, false, false);
        Campos(false);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txt_cargo_codigo.setText("");
        txt_cargo_nome.setText("");
        Botoes(true, false, false, false, false);
        Campos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tbl_cargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_cargoKeyReleased
        // TODO add your handling code here:
//        if (tbl_cargo.getSelectedRow() != -1) {
//            txt_cargo_codigo.setText(tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),0).toString());
//            txt_cargo_nome.setText(tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),1).toString());
//            txt_cargo_salario.setText(tbl_cargo.getValueAt(tbl_cargo.getSelectedRow(),2).toString());
//        }
//        Botoes(false, true, true, false, false);
    }//GEN-LAST:event_tbl_cargoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cargo;
    private javax.swing.JTextField txt_cargo_codigo;
    private javax.swing.JTextField txt_cargo_nome;
    // End of variables declaration//GEN-END:variables
}
